version: "3.9"
services:

  app:
    build: ./apps
    restart: always
    links:
      - db
    ports:
      - "3000"
    environment:
      - DB_HOST=db
      - DB_NAME=training
      - DB_USER=peserta
      - DB_PASS=password
    volumes:
      - app-data:/app/public/images

  db:
    image: "mariadb"
    restart: always
    links:
      - phpmyadmin
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=training
      - MYSQL_USER=peserta
      - MYSQL_PASSWORD=password
    volumes:
      - ./apps/database/:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin"
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db

  web:
    build: ./nginx
    restart: always
    ports:
    - "80:80"
    depends_on:
    - app

volumes:
  app-data:
  db-data:
    